version: 2

jobs:
  build:
    docker:
      - image: basisregisters/build-agent:latest
      - image: minio/minio:latest
        environment:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - image: mcr.microsoft.com/mssql/server:latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: E@syP@ssw0rd

    environment:
      MYGET_FEED: /F/basisregisters
      MYGET_FEED_USER: informatievlaanderen
      MYGET_HOST: https://informatievlaanderen.myget.org
      NUGET_HOST: https://www.nuget.org
      GIT_USERNAME: release-bot
      GIT_AUTHOR_NAME: release-bot
      GIT_COMMITTER_NAME: release-bot
      GIT_EMAIL: informatie.vlaanderen@vlaanderen.be
      GIT_AUTHOR_EMAIL: informatie.vlaanderen@vlaanderen.be
      GIT_COMMITTER_EMAIL: informatie.vlaanderen@vlaanderen.be
      CONFLUENCE_USERNAME: david.cumps@kb.vlaanderen.be
      SA_PASSWORD: E@syP@ssw0rd
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      CI: true

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - restore_cache:
          name: Restore Paket  cache
          keys:
            - v1-paket-{{ arch }}-{{ .Branch }}-{{ checksum "paket.dependencies" }}
            - v1-paket-{{ arch }}-{{ .Branch }}-
            - v1-paket-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install NPM dependencies (master)
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              npm install;
            fi

      - run:
          name: Run Semantic Release (master)
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              npx semantic-release;
            fi

      - run:
          name: Run Build (non-master)
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ];
            then
              echo 'export CI=true' >> ~/.bashrc
              source ~/.bashrc
              ./build.sh;
            fi

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - save_cache:
          name: Save Paket cache
          key: v1-paket-{{ arch }}-{{ .Branch }}-{{ checksum "paket.dependencies" }}
          paths:
            - ~/.nuget/packages
            - packages
