version: '3.9'
services:
  minio:
    image: 'bitnami/minio:latest'
    hostname: minio-server
    container_name: minio-server
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000:9000"
      - "9001:9001"