name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Build
    runs-on: ubuntu-latest

    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
          MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        ports:
          - 9000:9000
          - 9001:9001
        options: --name minio-server
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: E@syP@ssw0rd
        options: --name sql-server

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # needed for Sonar, default is 11 and is decprecated
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Parse repository name
      run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
      shell: bash

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.VBR_DOTNET_VERSION_9 }}
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    - name: .NET version
      shell: bash
      run: dotnet --info

    - name: Restore packages
      shell: bash
      run: |
        ./pre-restore.sh
        dotnet tool restore
        dotnet restore --locked-mode

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: ./.sonar/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
        
    - name: Install DotCover
      shell: bash
      run: |
        dotnet tool install --global JetBrains.dotCover.CommandLineTools
        
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir .sonar
        mkdir .sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
        
    - name: Sonar begin build & analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.VBR_SONAR_TOKEN }}
      shell: bash
      run: |
        ./.sonar/scanner/dotnet-sonarscanner begin /k:"Informatievlaanderen_blob-store" /o:"informatievlaanderen" /d:sonar.token="${{ secrets.VBR_SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html > /dev/null 2>&1

    - name: Build
      shell: bash
      run: |
        dotnet build --nologo --no-restore --no-incremental --configuration Debug Be.Vlaanderen.Basisregisters.BlobStore.sln

    - name: Test
      shell: bash
      run: dotnet dotCover cover-dotnet --ReportType=HTML --Output=dotCover.Output.html -- test --nologo --no-build Be.Vlaanderen.Basisregisters.BlobStore.sln
      env:
        SQL_SERVER: sql-server
        SA_PASSWORD: E@syP@ssw0rd
        MINIO_PORT: 9000
        MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
        MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

    - name: Sonar end build & analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.VBR_SONAR_TOKEN }}
      shell: bash
      run: |
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.VBR_SONAR_TOKEN }}" > /dev/null 2>&1
